# Generated by Django 5.1.2 on 2024-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReportApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereports',
            name='status',
            field=models.BooleanField(default=False, verbose_name=True),
        ),
    ]
